#!/usr/bin/env node
import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { buildLocalProfiles } from "./phase11-local-model.js";

const [inputDir, outputFile] = process.argv.slice(2);
if (!inputDir || !outputFile) {
  console.error("Usage: node tools/aggregate_phase11_local.mjs INPUT_DIR OUTPUT.sql");
  process.exit(2);
}
const files = (await readdir(inputDir)).filter((name) => name.endsWith(".json")).sort();
if (!files.length) throw new Error("集計できるdaily-v2 JSONがありません");
const payloads = [];
for (const file of files) payloads.push(JSON.parse(await readFile(resolve(inputDir, file), "utf8")));
const generatedAt = new Date();
const result = buildLocalProfiles(payloads, generatedAt.getTime());
if (!result.profiles.length) throw new Error("プロファイルが0件のためD1更新を中止しました");

const statements = ["-- generated by aggregate_phase11_local.mjs"];
appendUpserts(statements, "profiles", [
  "segment_key", "route_id", "direction_id", "from_stop_id", "to_stop_id", "day_type", "time_bin",
  "profile_seconds", "median_seconds", "p25_seconds", "p75_seconds", "mad_seconds", "sample_count", "confidence", "generated_at",
], result.profiles, ["segment_key", "day_type", "time_bin"]);
statements.push(`DELETE FROM profiles WHERE generated_at <> ${sql(generatedAt.toISOString())};`);
appendUpserts(statements, "weather_profiles", [
  "scope", "route_id", "direction_id", "weather_class", "temperature_band", "adjustment_ratio",
  "median_ratio", "p25_ratio", "p75_ratio", "sample_count", "confidence", "generated_at",
], result.weatherProfiles, ["scope", "route_id", "direction_id", "weather_class", "temperature_band"]);
statements.push(`DELETE FROM weather_profiles WHERE generated_at <> ${sql(generatedAt.toISOString())};`);
statements.push(`INSERT INTO job_status (job_name,status,started_at,completed_at,source_objects,profile_count,error)
VALUES ('profile-aggregation','complete',${sql(generatedAt.toISOString())},${sql(generatedAt.toISOString())},${result.sourceObjects},${result.profiles.length},NULL)
ON CONFLICT(job_name) DO UPDATE SET status=excluded.status,started_at=excluded.started_at,completed_at=excluded.completed_at,source_objects=excluded.source_objects,profile_count=excluded.profile_count,error=NULL;`);
await writeFile(outputFile, `${statements.join("\n")}\n`);
console.log(JSON.stringify({ ...result, profiles: result.profiles.length, weatherProfiles: result.weatherProfiles.length, outputFile }));

function appendUpserts(output, table, columns, rows, keys) {
  const updates = columns.filter((column) => !keys.includes(column)).map((column) => `${column}=excluded.${column}`).join(",");
  for (let index = 0; index < rows.length; index += 100) {
    const values = rows.slice(index, index + 100).map((row) => `(${columns.map((column) => sql(row[column])).join(",")})`);
    output.push(`INSERT INTO ${table} (${columns.join(",")}) VALUES\n${values.join(",\n")}\nON CONFLICT(${keys.join(",")}) DO UPDATE SET ${updates};`);
  }
}

function sql(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`非有限数はSQLへ出力できません: ${value}`);
    return String(value);
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}
